### PR TITLE
Use html5mode urls for displaying Store modals

### PR DESCRIPTION
**Pull request by fjvallarino**
This version updates urls to fix an issue caused by the switch to html5Mode on Store. 

During deployment to staging, an issue running test cases arose. After a few hours of research, the problem was found: gulp-protractor references protractor with a "*" wildcard, which always pulls the latest version. Forcing protractor's version to 1.6.1 (the one used at the time of the last successful build), fixes the problem. Since this is a transitive dependency (three levels down), it forced me to use npm shrinkwrap. I'm writing all this down in case you face the same issue.

@tejohnso @alex-deaconu please review

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@fjvallarino I don't follow. Why do you need to use this shrinkwrap thing? It doesn't make sense to add an additional dependency just for that... 

Can't you just lock the protractor version? 

Thanks.

**Comment by fjvallarino** [comment]
@alex-deaconu Since this is a third-party dependency (widget-tester -> gulp-protractor -> protractor), I can't change the version. The only way to force a specific version on a sub dependency is using npm shrinkwrap on the currently working dependency tree (that is, with protractor's version manually replaced/installed inside gulp-protractor's directory). The alternative is not using shrinkwrap and replacing protractor with a shell script, but I think that's even worse (easy to do on Circle, but not for local)

**Comment by fjvallarino** [comment]
@alex-deaconu @tejohnso Just to clarify, all I'm doing with shrinkwrap is locking the version of protractor. Unfortunately, it also means locking the version of all the other dependencies (so we'll have to run npm shrinkwrap again if we update any dependency).

**Comment by alex-deaconu** [comment]
@fjvallarino not acceptable. That is not the issue at all. See #41. This fixes the e2e tests, no need for shrinkwrap, etc.

You had it in your PR, I'm curious why you had to add all that extra stuff. Please rebase and remove.

Thanks.

**Comment by tejohnso** [comment]
@alex-deaconu are you sure the tests are fixed and not false passes due to not waiting for promise resolution?

If that's the case 
@fjvallarino maybe instead of fixing it at an old version you can try to get it working with the latest protractor?

**Comment by alex-deaconu** [comment]
@tejohnso the issue is there is no promise resolution! No done(); is ever called. I'm not really sure how these tests were working in the first place!

**Comment by fjvallarino** [comment]
@alex-deaconu I'm puzzled about why those test work on the previous version of protractor, but it's definitely better to avoid shrinkwrap. I'll rebase.

**Comment by alex-deaconu** [comment]
@fjvallarino thanks!

**Comment by fjvallarino** [comment]
@tejohnso @alex-deaconu please review

**Comment by alex-deaconu** [comment]
:+1: . @fjvallarino thanks for investigating lint and e2e issues on the project.

**Pull request merged**
